<?xml version="1.0" encoding="UTF-8"?>

<!--
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.xwiki.contrib</groupId>
    <artifactId>parent-platform</artifactId>
    <version>17.10.0-3</version>
  </parent>
  <groupId>org.xwiki.contrib</groupId>
  <artifactId>application-rfc</artifactId>
  <version>2.0-SNAPSHOT</version>
  <name>RFC Application - Parent POM</name>
  <packaging>pom</packaging>
  <description>Author documents that share common traits with IETF's Request for Comments (RFC).</description>
  <url>https://extensions.xwiki.org/xwiki/bin/view/Extension/RFC%20Application</url>
  <properties>
    <!-- JIRA project of the application (to be created). Automatic JIRA release stays disabled until the project
         exists. -->
    <xwiki.issueManagement.jira.id>RFC</xwiki.issueManagement.jira.id>
    <!-- No Java code in this project: nothing to check with Checkstyle or Revapi -->
    <xwiki.checkstyle.skip>true</xwiki.checkstyle.skip>
    <xwiki.revapi.skip>true</xwiki.revapi.skip>
  </properties>
  <scm>
    <connection>scm:git:git://github.com/xwiki-contrib/application-rfc.git</connection>
    <developerConnection>scm:git:git@github.com:xwiki-contrib/application-rfc.git</developerConnection>
    <url>https://github.com/xwiki-contrib/application-rfc/tree/master</url>
    <tag>HEAD</tag>
  </scm>
  <developers>
    <developer>
      <id>ciaens</id>
      <name>Clément Christiaens</name>
    </developer>
  </developers>
  <contributors>
    <contributor>
      <name>Fabio Mancinelli</name>
      <roles>
        <role>Original author</role>
      </roles>
    </contributor>
  </contributors>
  <modules>
    <module>application-rfc-ui</module>
  </modules>
</project>
